# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

"""
Open-RMF style migration API
"""
from __future__ import annotations
import pybind11_stubgen.typing_ext
import typing
import vda5050_core._core.client
import vda5050_core._core.types
__all__: list[str] = ['ActivityIdentifier', 'Adapter', 'CommandExecution', 'Destination', 'FleetConfiguration', 'FleetUpdateHandle', 'RobotCallbacks', 'RobotConfiguration', 'RobotState', 'RobotUpdateHandle']
class ActivityIdentifier:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ActivityIdentifier) -> bool:
        ...
    def __ne__(self, arg0: ActivityIdentifier) -> bool:
        ...
class Adapter:
    @staticmethod
    def make() -> Adapter:
        ...
    def add_vda5050_fleet(self, configuration: FleetConfiguration) -> FleetUpdateHandle:
        ...
    def start(self) -> None:
        ...
    def stop(self) -> None:
        ...
class CommandExecution:
    def failed(self, arg0: str) -> None:
        ...
    def finished(self) -> None:
        ...
    def is_finished(self) -> bool:
        ...
    def okay(self) -> bool:
        ...
    @property
    def identifier(self) -> ActivityIdentifier:
        ...
class Destination:
    @property
    def graph_index(self) -> int | None:
        ...
    @property
    def map(self) -> str:
        ...
    @property
    def name(self) -> str | None:
        ...
    @property
    def position(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]:
        ...
    @property
    def speed_limit(self) -> float | None:
        ...
    @property
    def xy(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    @property
    def yaw(self) -> float:
        ...
class FleetConfiguration:
    broker_uri: str
    client_id_prefix: str
    fleet_name: str
    update_interval: int
    def __init__(self, fleet_name: str, broker_uri: str, client_id_prefix: str, update_interval: int = 30) -> None:
        ...
    def add_known_robot_configuration(self, arg0: str, arg1: RobotConfiguration) -> None:
        ...
    def get_known_robot_configuration(self, arg0: str) -> RobotConfiguration | None:
        ...
    @property
    def known_robots(self) -> list[str]:
        ...
class FleetUpdateHandle:
    def add_robot(self, arg0: str, arg1: RobotState, arg2: RobotConfiguration, arg3: RobotCallbacks) -> RobotUpdateHandle:
        ...
class RobotCallbacks:
    localize: typing.Callable[[Destination, CommandExecution], None]
    def __init__(self, navigate: typing.Callable[[Destination, CommandExecution], None], stop: typing.Callable[[ActivityIdentifier], None], action_executor: typing.Callable[[str, json, CommandExecution], None]) -> None:
        ...
    @property
    def action_executor(self) -> typing.Callable[[str, json, CommandExecution], None]:
        ...
    @property
    def navigate(self) -> typing.Callable[[Destination, CommandExecution], None]:
        ...
    @property
    def stop(self) -> typing.Callable[[ActivityIdentifier], None]:
        ...
class RobotConfiguration:
    factsheet: vda5050_core._core.types.Factsheet | None
    interface_name: str
    manufacturer: str
    serial_number: str
    version: str
    def __init__(self, manufacturer: str, serial_number: str, interface_name: str = 'uagv', version: str = '2.0.0') -> None:
        ...
class RobotState:
    battery_state_of_charge: float
    map: str
    position: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)]
    def __init__(self, map: str, position: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(3)], battery_soc: float) -> None:
        ...
class RobotUpdateHandle:
    def more(self) -> vda5050_core._core.client.StateManager:
        ...
    def update(self, arg0: RobotState, arg1: ActivityIdentifier) -> None:
        ...
