# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

"""
VDA5050 MQTT transport layer
"""
from __future__ import annotations
import typing
__all__: list[str] = ['MqttClientInterface', 'create_default_client_shared']
class MqttClientInterface:
    def __init__(self) -> None:
        ...
    def connect(self) -> None:
        ...
    def connected(self) -> bool:
        ...
    def disconnect(self) -> None:
        ...
    def publish(self, topic: str, message: str, qos: int, retain: bool = False) -> None:
        ...
    def set_connected_callback(self, handler: typing.Callable[[str], None]) -> None:
        ...
    def set_connection_lost_callback(self, handler: typing.Callable[[str], None]) -> None:
        ...
    def set_will(self, topic: str, message: str, qos: int, retain: bool = True) -> None:
        ...
    def subscribe(self, topic: str, handler: typing.Callable[[str, str], None], qos: int) -> None:
        ...
    def unsubscribe(self, topic: str) -> None:
        ...
def create_default_client_shared(broker_address: str, client_id: str) -> MqttClientInterface:
    """
    Create a Paho-backed MQTT client shared_ptr.
    """
