# This file is automatically generated by pybind11-stubgen and generate_stubs.py
#
# Automatically generated files do not have a copyright

"""
VDA5050 types
"""
from __future__ import annotations
import typing
__all__: list[str] = ['AGVAction', 'AGVClass', 'AGVGeometry', 'AGVKinematic', 'AGVPosition', 'Action', 'ActionParameter', 'ActionParameterFactsheet', 'ActionScope', 'ActionState', 'ActionStatus', 'BatteryState', 'BlockingType', 'BoundingBoxReference', 'Connection', 'ConnectionState', 'ControlPoint', 'EStop', 'Edge', 'EdgeState', 'Envelope2d', 'Envelope3d', 'Error', 'ErrorLevel', 'ErrorReference', 'Factsheet', 'Header', 'Info', 'InfoLevel', 'InfoReference', 'InstantActions', 'Load', 'LoadDimensions', 'LoadSet', 'LoadSpecification', 'MaxArrayLens', 'MaxStringLens', 'Node', 'NodePosition', 'NodeState', 'OperatingMode', 'OptionalParameter', 'Order', 'OrientationType', 'PhysicalParameters', 'PolygonPoint', 'Position', 'ProtocolFeatures', 'ProtocolLimits', 'SafetyState', 'State', 'Support', 'Timing', 'Trajectory', 'TypeSpecification', 'ValueDataType', 'Velocity', 'Visualization', 'WheelDefinition', 'WheelDefinitionType']
class AGVAction:
    __hash__: typing.ClassVar[None] = None
    action_description: str | None
    action_parameters: list[ActionParameterFactsheet] | None
    action_scopes: list[ActionScope]
    action_type: str
    blocking_types: list[BlockingType] | None
    result_description: str | None
    @staticmethod
    def from_json(arg0: json) -> AGVAction:
        ...
    def __eq__(self, arg0: AGVAction) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: AGVAction) -> bool:
        ...
    def json(self) -> json:
        ...
class AGVClass:
    """
    Members:
    
      FORKLIFT
    
      CONVEYOR
    
      TUGGER
    
      CARRIER
    """
    CARRIER: typing.ClassVar[AGVClass]  # value = <AGVClass.CARRIER: 3>
    CONVEYOR: typing.ClassVar[AGVClass]  # value = <AGVClass.CONVEYOR: 1>
    FORKLIFT: typing.ClassVar[AGVClass]  # value = <AGVClass.FORKLIFT: 0>
    TUGGER: typing.ClassVar[AGVClass]  # value = <AGVClass.TUGGER: 2>
    __members__: typing.ClassVar[dict[str, AGVClass]]  # value = {'FORKLIFT': <AGVClass.FORKLIFT: 0>, 'CONVEYOR': <AGVClass.CONVEYOR: 1>, 'TUGGER': <AGVClass.TUGGER: 2>, 'CARRIER': <AGVClass.CARRIER: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class AGVGeometry:
    __hash__: typing.ClassVar[None] = None
    envelopes2d: list[Envelope2d] | None
    envelopes3d: list[Envelope3d] | None
    wheel_definitions: list[WheelDefinition] | None
    @staticmethod
    def from_json(arg0: json) -> AGVGeometry:
        ...
    def __eq__(self, arg0: AGVGeometry) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: AGVGeometry) -> bool:
        ...
    def json(self) -> json:
        ...
class AGVKinematic:
    """
    Members:
    
      DIFF
    
      OMNI
    
      THREEWHEEL
    """
    DIFF: typing.ClassVar[AGVKinematic]  # value = <AGVKinematic.DIFF: 0>
    OMNI: typing.ClassVar[AGVKinematic]  # value = <AGVKinematic.OMNI: 1>
    THREEWHEEL: typing.ClassVar[AGVKinematic]  # value = <AGVKinematic.THREEWHEEL: 2>
    __members__: typing.ClassVar[dict[str, AGVKinematic]]  # value = {'DIFF': <AGVKinematic.DIFF: 0>, 'OMNI': <AGVKinematic.OMNI: 1>, 'THREEWHEEL': <AGVKinematic.THREEWHEEL: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class AGVPosition:
    __hash__: typing.ClassVar[None] = None
    deviation_range: float | None
    localization_score: float | None
    map_description: str | None
    map_id: str
    position_initialized: bool
    theta: float
    x: float
    y: float
    @staticmethod
    def from_json(arg0: json) -> AGVPosition:
        ...
    def __eq__(self, arg0: AGVPosition) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: AGVPosition) -> bool:
        ...
    def json(self) -> json:
        ...
class Action:
    __hash__: typing.ClassVar[None] = None
    action_description: str | None
    action_id: str
    action_parameters: list[ActionParameter] | None
    action_type: str
    blocking_type: BlockingType
    @staticmethod
    def from_json(arg0: json) -> Action:
        ...
    def __eq__(self, arg0: Action) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Action) -> bool:
        ...
    def json(self) -> json:
        ...
class ActionParameter:
    __hash__: typing.ClassVar[None] = None
    key: str
    value: str
    @staticmethod
    def from_json(arg0: json) -> ActionParameter:
        ...
    def __eq__(self, arg0: ActionParameter) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ActionParameter) -> bool:
        ...
    def json(self) -> json:
        ...
class ActionParameterFactsheet:
    __hash__: typing.ClassVar[None] = None
    description: str | None
    is_optional: bool | None
    key: str
    value_data_type: ValueDataType
    @staticmethod
    def from_json(arg0: json) -> ActionParameterFactsheet:
        ...
    def __eq__(self, arg0: ActionParameterFactsheet) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ActionParameterFactsheet) -> bool:
        ...
    def json(self) -> json:
        ...
class ActionScope:
    """
    Members:
    
      INSTANT
    
      NODE
    
      EDGE
    """
    EDGE: typing.ClassVar[ActionScope]  # value = <ActionScope.EDGE: 2>
    INSTANT: typing.ClassVar[ActionScope]  # value = <ActionScope.INSTANT: 0>
    NODE: typing.ClassVar[ActionScope]  # value = <ActionScope.NODE: 1>
    __members__: typing.ClassVar[dict[str, ActionScope]]  # value = {'INSTANT': <ActionScope.INSTANT: 0>, 'NODE': <ActionScope.NODE: 1>, 'EDGE': <ActionScope.EDGE: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ActionState:
    __hash__: typing.ClassVar[None] = None
    action_description: str | None
    action_id: str
    action_status: ActionStatus
    action_type: str | None
    result_description: str | None
    @staticmethod
    def from_json(arg0: json) -> ActionState:
        ...
    def __eq__(self, arg0: ActionState) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ActionState) -> bool:
        ...
    def json(self) -> json:
        ...
class ActionStatus:
    """
    Members:
    
      WAITING
    
      INITIALIZING
    
      RUNNING
    
      PAUSED
    
      FINISHED
    
      FAILED
    """
    FAILED: typing.ClassVar[ActionStatus]  # value = <ActionStatus.FAILED: 5>
    FINISHED: typing.ClassVar[ActionStatus]  # value = <ActionStatus.FINISHED: 4>
    INITIALIZING: typing.ClassVar[ActionStatus]  # value = <ActionStatus.INITIALIZING: 1>
    PAUSED: typing.ClassVar[ActionStatus]  # value = <ActionStatus.PAUSED: 3>
    RUNNING: typing.ClassVar[ActionStatus]  # value = <ActionStatus.RUNNING: 2>
    WAITING: typing.ClassVar[ActionStatus]  # value = <ActionStatus.WAITING: 0>
    __members__: typing.ClassVar[dict[str, ActionStatus]]  # value = {'WAITING': <ActionStatus.WAITING: 0>, 'INITIALIZING': <ActionStatus.INITIALIZING: 1>, 'RUNNING': <ActionStatus.RUNNING: 2>, 'PAUSED': <ActionStatus.PAUSED: 3>, 'FINISHED': <ActionStatus.FINISHED: 4>, 'FAILED': <ActionStatus.FAILED: 5>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class BatteryState:
    __hash__: typing.ClassVar[None] = None
    battery_charge: float
    battery_health: int | None
    battery_voltage: float | None
    charging: bool
    reach: int | None
    @staticmethod
    def from_json(arg0: json) -> BatteryState:
        ...
    def __eq__(self, arg0: BatteryState) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: BatteryState) -> bool:
        ...
    def json(self) -> json:
        ...
class BlockingType:
    """
    Members:
    
      NONE
    
      SOFT
    
      HARD
    """
    HARD: typing.ClassVar[BlockingType]  # value = <BlockingType.HARD: 2>
    NONE: typing.ClassVar[BlockingType]  # value = <BlockingType.NONE: 0>
    SOFT: typing.ClassVar[BlockingType]  # value = <BlockingType.SOFT: 1>
    __members__: typing.ClassVar[dict[str, BlockingType]]  # value = {'NONE': <BlockingType.NONE: 0>, 'SOFT': <BlockingType.SOFT: 1>, 'HARD': <BlockingType.HARD: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class BoundingBoxReference:
    __hash__: typing.ClassVar[None] = None
    theta: float | None
    x: float
    y: float
    z: float
    @staticmethod
    def from_json(arg0: json) -> BoundingBoxReference:
        ...
    def __eq__(self, arg0: BoundingBoxReference) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: BoundingBoxReference) -> bool:
        ...
    def json(self) -> json:
        ...
class Connection:
    __hash__: typing.ClassVar[None] = None
    connection_state: ConnectionState
    header: Header
    @staticmethod
    def from_json(arg0: json) -> Connection:
        ...
    def __eq__(self, arg0: Connection) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Connection) -> bool:
        ...
    def json(self) -> json:
        ...
class ConnectionState:
    """
    Members:
    
      ONLINE
    
      OFFLINE
    
      CONNECTIONBROKEN
    """
    CONNECTIONBROKEN: typing.ClassVar[ConnectionState]  # value = <ConnectionState.CONNECTIONBROKEN: 2>
    OFFLINE: typing.ClassVar[ConnectionState]  # value = <ConnectionState.OFFLINE: 1>
    ONLINE: typing.ClassVar[ConnectionState]  # value = <ConnectionState.ONLINE: 0>
    __members__: typing.ClassVar[dict[str, ConnectionState]]  # value = {'ONLINE': <ConnectionState.ONLINE: 0>, 'OFFLINE': <ConnectionState.OFFLINE: 1>, 'CONNECTIONBROKEN': <ConnectionState.CONNECTIONBROKEN: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ControlPoint:
    __hash__: typing.ClassVar[None] = None
    weight: float
    x: float
    y: float
    @staticmethod
    def from_json(arg0: json) -> ControlPoint:
        ...
    def __eq__(self, arg0: ControlPoint) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ControlPoint) -> bool:
        ...
    def json(self) -> json:
        ...
class EStop:
    """
    Members:
    
      AUTOACK
    
      MANUAL
    
      REMOTE
    
      NONE
    """
    AUTOACK: typing.ClassVar[EStop]  # value = <EStop.AUTOACK: 0>
    MANUAL: typing.ClassVar[EStop]  # value = <EStop.MANUAL: 1>
    NONE: typing.ClassVar[EStop]  # value = <EStop.NONE: 3>
    REMOTE: typing.ClassVar[EStop]  # value = <EStop.REMOTE: 2>
    __members__: typing.ClassVar[dict[str, EStop]]  # value = {'AUTOACK': <EStop.AUTOACK: 0>, 'MANUAL': <EStop.MANUAL: 1>, 'REMOTE': <EStop.REMOTE: 2>, 'NONE': <EStop.NONE: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Edge:
    __hash__: typing.ClassVar[None] = None
    actions: list[Action]
    direction: str | None
    edge_description: str | None
    edge_id: str
    end_node_id: str
    length: float | None
    max_height: float | None
    max_rotation_speed: float | None
    max_speed: float | None
    min_height: float | None
    orientation: float | None
    orientation_type: OrientationType | None
    released: bool
    rotation_allowed: bool | None
    sequence_id: int
    start_node_id: str
    trajectory: Trajectory | None
    @staticmethod
    def from_json(arg0: json) -> Edge:
        ...
    def __eq__(self, arg0: Edge) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Edge) -> bool:
        ...
    def json(self) -> json:
        ...
class EdgeState:
    __hash__: typing.ClassVar[None] = None
    edge_description: str | None
    edge_id: str
    released: bool
    sequence_id: int
    trajectory: Trajectory | None
    @staticmethod
    def from_json(arg0: json) -> EdgeState:
        ...
    def __eq__(self, arg0: EdgeState) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: EdgeState) -> bool:
        ...
    def json(self) -> json:
        ...
class Envelope2d:
    __hash__: typing.ClassVar[None] = None
    description: str | None
    polygon_points: list[PolygonPoint]
    set: str
    @staticmethod
    def from_json(arg0: json) -> Envelope2d:
        ...
    def __eq__(self, arg0: Envelope2d) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Envelope2d) -> bool:
        ...
    def json(self) -> json:
        ...
class Envelope3d:
    __hash__: typing.ClassVar[None] = None
    data: str | None
    description: str | None
    format: str
    set: str
    url: str | None
    @staticmethod
    def from_json(arg0: json) -> Envelope3d:
        ...
    def __eq__(self, arg0: Envelope3d) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Envelope3d) -> bool:
        ...
    def json(self) -> json:
        ...
class Error:
    __hash__: typing.ClassVar[None] = None
    error_description: str | None
    error_level: ErrorLevel
    error_references: list[ErrorReference] | None
    error_type: str
    @staticmethod
    def from_json(arg0: json) -> Error:
        ...
    def __eq__(self, arg0: Error) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Error) -> bool:
        ...
    def json(self) -> json:
        ...
class ErrorLevel:
    """
    Members:
    
      WARNING
    
      FATAL
    """
    FATAL: typing.ClassVar[ErrorLevel]  # value = <ErrorLevel.FATAL: 1>
    WARNING: typing.ClassVar[ErrorLevel]  # value = <ErrorLevel.WARNING: 0>
    __members__: typing.ClassVar[dict[str, ErrorLevel]]  # value = {'WARNING': <ErrorLevel.WARNING: 0>, 'FATAL': <ErrorLevel.FATAL: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ErrorReference:
    __hash__: typing.ClassVar[None] = None
    reference_key: str
    reference_value: str
    @staticmethod
    def from_json(arg0: json) -> ErrorReference:
        ...
    def __eq__(self, arg0: ErrorReference) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ErrorReference) -> bool:
        ...
    def json(self) -> json:
        ...
class Factsheet:
    __hash__: typing.ClassVar[None] = None
    agv_geometry: AGVGeometry
    header: Header
    load_specification: LoadSpecification
    localization_parameters: str | None
    physical_parameters: PhysicalParameters
    protocol_features: ProtocolFeatures
    protocol_limits: ProtocolLimits
    type_specification: TypeSpecification
    @staticmethod
    def from_json(arg0: json) -> Factsheet:
        ...
    def __eq__(self, arg0: Factsheet) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Factsheet) -> bool:
        ...
    def json(self) -> json:
        ...
class Header:
    __hash__: typing.ClassVar[None] = None
    header_id: int
    manufacturer: str
    serial_number: str
    timestamp: float
    version: str
    @staticmethod
    def from_json(arg0: json) -> Header:
        ...
    def __eq__(self, arg0: Header) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Header) -> bool:
        ...
    def json(self) -> json:
        ...
class Info:
    __hash__: typing.ClassVar[None] = None
    info_description: str | None
    info_level: InfoLevel
    info_references: list[InfoReference] | None
    info_type: str
    @staticmethod
    def from_json(arg0: json) -> Info:
        ...
    def __eq__(self, arg0: Info) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Info) -> bool:
        ...
    def json(self) -> json:
        ...
class InfoLevel:
    """
    Members:
    
      DEBUG
    
      INFO
    """
    DEBUG: typing.ClassVar[InfoLevel]  # value = <InfoLevel.DEBUG: 0>
    INFO: typing.ClassVar[InfoLevel]  # value = <InfoLevel.INFO: 1>
    __members__: typing.ClassVar[dict[str, InfoLevel]]  # value = {'DEBUG': <InfoLevel.DEBUG: 0>, 'INFO': <InfoLevel.INFO: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class InfoReference:
    __hash__: typing.ClassVar[None] = None
    reference_key: str
    reference_value: str
    @staticmethod
    def from_json(arg0: json) -> InfoReference:
        ...
    def __eq__(self, arg0: InfoReference) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: InfoReference) -> bool:
        ...
    def json(self) -> json:
        ...
class InstantActions:
    __hash__: typing.ClassVar[None] = None
    actions: list[Action]
    header: Header
    @staticmethod
    def from_json(arg0: json) -> InstantActions:
        ...
    def __eq__(self, arg0: InstantActions) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: InstantActions) -> bool:
        ...
    def json(self) -> json:
        ...
class Load:
    __hash__: typing.ClassVar[None] = None
    bounding_box_reference: BoundingBoxReference | None
    load_dimensions: LoadDimensions | None
    load_id: str | None
    load_position: str | None
    load_type: str | None
    weight: float | None
    @staticmethod
    def from_json(arg0: json) -> Load:
        ...
    def __eq__(self, arg0: Load) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Load) -> bool:
        ...
    def json(self) -> json:
        ...
class LoadDimensions:
    __hash__: typing.ClassVar[None] = None
    height: float | None
    length: float
    width: float
    @staticmethod
    def from_json(arg0: json) -> LoadDimensions:
        ...
    def __eq__(self, arg0: LoadDimensions) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: LoadDimensions) -> bool:
        ...
    def json(self) -> json:
        ...
class LoadSet:
    __hash__: typing.ClassVar[None] = None
    agv_acceleration_limit: float | None
    agv_deceleration_limit: float | None
    agv_speed_limit: float | None
    bounding_box_reference: BoundingBoxReference | None
    description: str | None
    drop_time: float | None
    load_dimensions: LoadDimensions | None
    load_positions: list[str] | None
    load_type: str
    max_load_handling_depth: float | None
    max_load_handling_height: float | None
    max_load_handling_tilt: float | None
    max_weight: float | None
    min_load_handling_depth: float | None
    min_load_handling_height: float | None
    min_load_handling_tilt: float | None
    pick_time: float | None
    set_name: str
    @staticmethod
    def from_json(arg0: json) -> LoadSet:
        ...
    def __eq__(self, arg0: LoadSet) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: LoadSet) -> bool:
        ...
    def json(self) -> json:
        ...
class LoadSpecification:
    __hash__: typing.ClassVar[None] = None
    load_positions: list[str] | None
    load_sets: list[LoadSet] | None
    @staticmethod
    def from_json(arg0: json) -> LoadSpecification:
        ...
    def __eq__(self, arg0: LoadSpecification) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: LoadSpecification) -> bool:
        ...
    def json(self) -> json:
        ...
class MaxArrayLens:
    __hash__: typing.ClassVar[None] = None
    actions_actions_parameters: int | None
    edge_actions: int | None
    error_error_references: int | None
    information_info_references: int | None
    instant_actions: int | None
    node_actions: int | None
    order_edges: int | None
    order_nodes: int | None
    state_action_states: int | None
    state_edge_states: int | None
    state_errors: int | None
    state_information: int | None
    state_loads: int | None
    state_node_states: int | None
    trajectory_control_points: int | None
    trajectory_knot_vector: int | None
    @staticmethod
    def from_json(arg0: json) -> MaxArrayLens:
        ...
    def __eq__(self, arg0: MaxArrayLens) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: MaxArrayLens) -> bool:
        ...
    def json(self) -> json:
        ...
class MaxStringLens:
    __hash__: typing.ClassVar[None] = None
    enum_len: int | None
    id_len: int | None
    id_numerical_only: bool | None
    load_id_len: int | None
    msg_len: int | None
    topic_elem_len: int | None
    topic_serial_len: int | None
    @staticmethod
    def from_json(arg0: json) -> MaxStringLens:
        ...
    def __eq__(self, arg0: MaxStringLens) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: MaxStringLens) -> bool:
        ...
    def json(self) -> json:
        ...
class Node:
    __hash__: typing.ClassVar[None] = None
    actions: list[Action]
    node_description: str | None
    node_id: str
    node_position: NodePosition | None
    released: bool
    sequence_id: int
    @staticmethod
    def from_json(arg0: json) -> Node:
        ...
    def __eq__(self, arg0: Node) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Node) -> bool:
        ...
    def json(self) -> json:
        ...
class NodePosition:
    __hash__: typing.ClassVar[None] = None
    allowed_deviation_theta: float | None
    allowed_deviation_x_y: float | None
    map_description: str | None
    map_id: str
    theta: float | None
    x: float
    y: float
    @staticmethod
    def from_json(arg0: json) -> NodePosition:
        ...
    def __eq__(self, arg0: NodePosition) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: NodePosition) -> bool:
        ...
    def json(self) -> json:
        ...
class NodeState:
    __hash__: typing.ClassVar[None] = None
    node_description: str | None
    node_id: str
    node_position: NodePosition | None
    released: bool
    sequence_id: int
    @staticmethod
    def from_json(arg0: json) -> NodeState:
        ...
    def __eq__(self, arg0: NodeState) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: NodeState) -> bool:
        ...
    def json(self) -> json:
        ...
class OperatingMode:
    """
    Members:
    
      AUTOMATIC
    
      SEMIAUTOMATIC
    
      MANUAL
    
      SERVICE
    
      TEACHIN
    """
    AUTOMATIC: typing.ClassVar[OperatingMode]  # value = <OperatingMode.AUTOMATIC: 0>
    MANUAL: typing.ClassVar[OperatingMode]  # value = <OperatingMode.MANUAL: 2>
    SEMIAUTOMATIC: typing.ClassVar[OperatingMode]  # value = <OperatingMode.SEMIAUTOMATIC: 1>
    SERVICE: typing.ClassVar[OperatingMode]  # value = <OperatingMode.SERVICE: 3>
    TEACHIN: typing.ClassVar[OperatingMode]  # value = <OperatingMode.TEACHIN: 4>
    __members__: typing.ClassVar[dict[str, OperatingMode]]  # value = {'AUTOMATIC': <OperatingMode.AUTOMATIC: 0>, 'SEMIAUTOMATIC': <OperatingMode.SEMIAUTOMATIC: 1>, 'MANUAL': <OperatingMode.MANUAL: 2>, 'SERVICE': <OperatingMode.SERVICE: 3>, 'TEACHIN': <OperatingMode.TEACHIN: 4>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class OptionalParameter:
    __hash__: typing.ClassVar[None] = None
    description: str | None
    parameter: str
    support: Support
    @staticmethod
    def from_json(arg0: json) -> OptionalParameter:
        ...
    def __eq__(self, arg0: OptionalParameter) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: OptionalParameter) -> bool:
        ...
    def json(self) -> json:
        ...
class Order:
    __hash__: typing.ClassVar[None] = None
    edges: list[Edge]
    header: Header
    nodes: list[Node]
    order_id: str
    order_update_id: int
    zone_set_id: str | None
    @staticmethod
    def from_json(arg0: json) -> Order:
        ...
    def __eq__(self, arg0: Order) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Order) -> bool:
        ...
    def json(self) -> json:
        ...
class OrientationType:
    """
    Members:
    
      GLOBAL
    
      TANGENTIAL
    """
    GLOBAL: typing.ClassVar[OrientationType]  # value = <OrientationType.GLOBAL: 0>
    TANGENTIAL: typing.ClassVar[OrientationType]  # value = <OrientationType.TANGENTIAL: 1>
    __members__: typing.ClassVar[dict[str, OrientationType]]  # value = {'GLOBAL': <OrientationType.GLOBAL: 0>, 'TANGENTIAL': <OrientationType.TANGENTIAL: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class PhysicalParameters:
    __hash__: typing.ClassVar[None] = None
    acceleration_max: float
    angular_speed_max: float | None
    angular_speed_min: float | None
    deceleration_max: float
    height_max: float
    height_min: float
    length: float
    speed_max: float
    speed_min: float
    width: float
    @staticmethod
    def from_json(arg0: json) -> PhysicalParameters:
        ...
    def __eq__(self, arg0: PhysicalParameters) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: PhysicalParameters) -> bool:
        ...
    def json(self) -> json:
        ...
class PolygonPoint:
    __hash__: typing.ClassVar[None] = None
    x: float
    y: float
    @staticmethod
    def from_json(arg0: json) -> PolygonPoint:
        ...
    def __eq__(self, arg0: PolygonPoint) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: PolygonPoint) -> bool:
        ...
    def json(self) -> json:
        ...
class Position:
    __hash__: typing.ClassVar[None] = None
    theta: float | None
    x: float
    y: float
    @staticmethod
    def from_json(arg0: json) -> Position:
        ...
    def __eq__(self, arg0: Position) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Position) -> bool:
        ...
    def json(self) -> json:
        ...
class ProtocolFeatures:
    __hash__: typing.ClassVar[None] = None
    agv_actions: list[AGVAction]
    optional_parameters: list[OptionalParameter]
    @staticmethod
    def from_json(arg0: json) -> ProtocolFeatures:
        ...
    def __eq__(self, arg0: ProtocolFeatures) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ProtocolFeatures) -> bool:
        ...
    def json(self) -> json:
        ...
class ProtocolLimits:
    __hash__: typing.ClassVar[None] = None
    max_array_lens: MaxArrayLens
    max_string_lens: MaxStringLens
    timing: Timing
    @staticmethod
    def from_json(arg0: json) -> ProtocolLimits:
        ...
    def __eq__(self, arg0: ProtocolLimits) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: ProtocolLimits) -> bool:
        ...
    def json(self) -> json:
        ...
class SafetyState:
    __hash__: typing.ClassVar[None] = None
    e_stop: EStop
    field_violation: bool
    @staticmethod
    def from_json(arg0: json) -> SafetyState:
        ...
    def __eq__(self, arg0: SafetyState) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: SafetyState) -> bool:
        ...
    def json(self) -> json:
        ...
class State:
    __hash__: typing.ClassVar[None] = None
    action_states: list[ActionState]
    agv_position: AGVPosition | None
    battery_state: BatteryState
    distance_since_last_node: float | None
    driving: bool
    edge_states: list[EdgeState]
    errors: list[Error]
    header: Header
    information: list[Info] | None
    last_node_id: str
    last_node_sequence_id: int
    loads: list[Load] | None
    new_base_request: bool | None
    node_states: list[NodeState]
    operating_mode: OperatingMode
    order_id: str
    order_update_id: int
    paused: bool | None
    safety_state: SafetyState
    velocity: Velocity | None
    zone_set_id: str | None
    @staticmethod
    def from_json(arg0: json) -> State:
        ...
    def __eq__(self, arg0: State) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: State) -> bool:
        ...
    def json(self) -> json:
        ...
class Support:
    """
    Members:
    
      SUPPORTED
    
      REQUIRED
    """
    REQUIRED: typing.ClassVar[Support]  # value = <Support.REQUIRED: 1>
    SUPPORTED: typing.ClassVar[Support]  # value = <Support.SUPPORTED: 0>
    __members__: typing.ClassVar[dict[str, Support]]  # value = {'SUPPORTED': <Support.SUPPORTED: 0>, 'REQUIRED': <Support.REQUIRED: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Timing:
    __hash__: typing.ClassVar[None] = None
    default_state_interval: float | None
    min_order_interval: float
    min_state_interval: float
    visualization_interval: float | None
    @staticmethod
    def from_json(arg0: json) -> Timing:
        ...
    def __eq__(self, arg0: Timing) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Timing) -> bool:
        ...
    def json(self) -> json:
        ...
class Trajectory:
    __hash__: typing.ClassVar[None] = None
    control_points: list[ControlPoint]
    degree: float
    knot_vector: list[float]
    @staticmethod
    def from_json(arg0: json) -> Trajectory:
        ...
    def __eq__(self, arg0: Trajectory) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Trajectory) -> bool:
        ...
    def json(self) -> json:
        ...
class TypeSpecification:
    __hash__: typing.ClassVar[None] = None
    agv_class: AGVClass
    agv_kinematic: AGVKinematic
    localization_types: list[str]
    max_load_mass: float
    navigation_types: list[str]
    series_description: str | None
    series_name: str
    @staticmethod
    def from_json(arg0: json) -> TypeSpecification:
        ...
    def __eq__(self, arg0: TypeSpecification) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: TypeSpecification) -> bool:
        ...
    def json(self) -> json:
        ...
class ValueDataType:
    """
    Members:
    
      BOOL
    
      NUMBER
    
      INTEGER
    
      FLOAT
    
      STRING
    
      OBJECT
    
      ARRAY
    """
    ARRAY: typing.ClassVar[ValueDataType]  # value = <ValueDataType.ARRAY: 6>
    BOOL: typing.ClassVar[ValueDataType]  # value = <ValueDataType.BOOL: 0>
    FLOAT: typing.ClassVar[ValueDataType]  # value = <ValueDataType.FLOAT: 3>
    INTEGER: typing.ClassVar[ValueDataType]  # value = <ValueDataType.INTEGER: 2>
    NUMBER: typing.ClassVar[ValueDataType]  # value = <ValueDataType.NUMBER: 1>
    OBJECT: typing.ClassVar[ValueDataType]  # value = <ValueDataType.OBJECT: 5>
    STRING: typing.ClassVar[ValueDataType]  # value = <ValueDataType.STRING: 4>
    __members__: typing.ClassVar[dict[str, ValueDataType]]  # value = {'BOOL': <ValueDataType.BOOL: 0>, 'NUMBER': <ValueDataType.NUMBER: 1>, 'INTEGER': <ValueDataType.INTEGER: 2>, 'FLOAT': <ValueDataType.FLOAT: 3>, 'STRING': <ValueDataType.STRING: 4>, 'OBJECT': <ValueDataType.OBJECT: 5>, 'ARRAY': <ValueDataType.ARRAY: 6>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Velocity:
    __hash__: typing.ClassVar[None] = None
    omega: float | None
    vx: float | None
    vy: float | None
    @staticmethod
    def from_json(arg0: json) -> Velocity:
        ...
    def __eq__(self, arg0: Velocity) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Velocity) -> bool:
        ...
    def json(self) -> json:
        ...
class Visualization:
    __hash__: typing.ClassVar[None] = None
    agv_position: AGVPosition | None
    header: Header
    velocity: Velocity | None
    @staticmethod
    def from_json(arg0: json) -> Visualization:
        ...
    def __eq__(self, arg0: Visualization) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: Visualization) -> bool:
        ...
    def json(self) -> json:
        ...
class WheelDefinition:
    __hash__: typing.ClassVar[None] = None
    center_displacement: float
    constraints: str | None
    diameter: float
    is_active_driven: bool
    is_active_steered: bool
    position: Position
    type: WheelDefinitionType
    width: float
    @staticmethod
    def from_json(arg0: json) -> WheelDefinition:
        ...
    def __eq__(self, arg0: WheelDefinition) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __ne__(self, arg0: WheelDefinition) -> bool:
        ...
    def json(self) -> json:
        ...
class WheelDefinitionType:
    """
    Members:
    
      DRIVE
    
      CASTER
    
      FIXED
    
      MECANUM
    """
    CASTER: typing.ClassVar[WheelDefinitionType]  # value = <WheelDefinitionType.CASTER: 1>
    DRIVE: typing.ClassVar[WheelDefinitionType]  # value = <WheelDefinitionType.DRIVE: 0>
    FIXED: typing.ClassVar[WheelDefinitionType]  # value = <WheelDefinitionType.FIXED: 2>
    MECANUM: typing.ClassVar[WheelDefinitionType]  # value = <WheelDefinitionType.MECANUM: 3>
    __members__: typing.ClassVar[dict[str, WheelDefinitionType]]  # value = {'DRIVE': <WheelDefinitionType.DRIVE: 0>, 'CASTER': <WheelDefinitionType.CASTER: 1>, 'FIXED': <WheelDefinitionType.FIXED: 2>, 'MECANUM': <WheelDefinitionType.MECANUM: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
