[build-system]
requires = ["scikit-build-core>=0.11", "pybind11<3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "vda5050_core"
version = "0.1.0rc1"
license = "Apache-2.0"
description = "Tools for VDA5050 development workflows"
authors = [
  { name = "Chen Bainian", email = "chen_bainian@a-star.edu.sg" },
  { name = "Saurabh Kamat", email = "saurabh_kamat@a-star.edu.sg" },
  { name = "Tinapat Game Limsila", email = "limsila.limsila@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]


[dependency-groups]
test = [
    "pytest>=8.0.2",
]
lint = [
    "ruff>=0.9",
]
dev = [
    { include-group = "test" },
    "pybind11-stubgen>=2.5.5",
]


[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
wheel.install-dir = "vda5050_core"

[tool.scikit-build.cmake.define]
BUILD_TESTING = "OFF"
BUILD_EXAMPLES = "OFF"
BUILD_PYTHON = "ON"
ENABLE_ROS2 = "OFF"

[tool.scikit-build.wheel.packages]
vda5050_core = "python/vda5050_core"

[tool.uv]
cache-keys = [
  { file = "include/**/*.{h,c,hpp,cpp}" }, 
  { file = "src/**/*.{h,c,hpp,cpp}" }, 
  { file = "python/**/*.{h,c,hpp,cpp,txt}" }, 
  { file = "CMakeLists.txt" },
]

[tool.ruff]
extend-exclude = ["*.pyi"]

[tool.cibuildwheel]
build-frontend = "build[uv]"
test-command = "pytest {project}/python/tests"
test-groups = ["test"]
before-build = [
  "bash ./scripts/install-native-deps.sh",
]

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
musllinux-x86_64-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"
